channels:
  - conda-forge
  - defaults
  - lambouj
dependencies:
  - python
  - pythonocc-core=7.5.1
  - pytorch
  - tqdm
  - igl
  - scikit-learn
  - pytorch-lightning=1.9.4
  - xlsxwriter
  - occwl=1.0.0
  - jupyter
  - pythreejs
  - tensorboard

